[package]
name = "infra"
version = "0.1.0"
edition = "2021"

[dependencies.sea-orm]
version = "0.5"
features = ["sqlx-postgres", "runtime-actix-rustls", "macros", "debug-print"]
default-features = false
