[package]
name = "services"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "3.3"
adapters = { path = "../adapters" }
anyhow = "1.0"
common = { path = "../common" }
log = "0.4"
log4rs = "1.0"
